# LOGGING
logging:
  file: target/vedci.log
  level:
    org.vedci: INFO
    org.springframework: WARN
    org.hibernate: WARN

# DATABASE
spring:
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none

# SECURITY
security:
  password:
    secret: ${SECURITY_PASSWORD_SECRET}

# LIQUIBASE
liquibase:
  enabled: true
  change-log: classpath:liquibase/config/master.xml
  url: ${JDBC_DATABASE_URL}
  user: ${JDBC_DATABASE_USERNAME}
  password: ${JDBC_DATABASE_PASSWORD}
